name: 'TestSpotlight'
description: 'An easier way to see what broke your code.'
author: 'DuncanScu'
branding:
  icon: 'percent'
  color: 'green'
inputs:
  github-token:
    description: 'GitHub repository token'
    required: true
  comment-title:
    description: 'Pull Request comment title'
    required: false
    default: 'Test Results'
  # results-path:
  #   description: 'Path to the directory containing trx files'
  #   required: true
  # file-type:
  #   description: 'File extension of the files'
  #   required: true
  groups:
    description: 'newline-seperated list of filesources. Groups must of be of format <source>:<extension>.'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
