name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  github-token:
    description: 'GitHub repository token'
    required: true
  results-path:
    description: 'Path to the directory containing trx files'
    required: true
  comment-title:
    description: 'Pull Request comment title'
    required: false
    default: 'Test Results'

runs:
  using: 'node16'
  main: 'dist/index.js'
