name: 'TestSpotlight'
description: 'An easier way to see what broke your code.'
author: 'DuncanScu'
branding:
  icon: 'percent'
  color: 'green'
inputs:
  github-token:
    description: 'GitHub repository token'
    required: true
  comment-title:
    description: 'Pull Request comment title'
    required: false
    default: 'Test Results'
  groups:
    description: 'Comma-seperated list of filesources:file exstension pairs. Groups must of be of format <source>:<extension>.'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
