name: 'TestSpotlight'
description: 'An easier way to see what broke your code.'
author: 'DuncanScu'
branding:
  icon: 'percent'
  color: 'green'
inputs:
  github-token:
    description: 'GitHub repository token'
    required: true
  comment-title:
    description: 'Pull Request comment title'
    required: false
    default: 'Test Results'
  results-path:
    description: 'Path to the directory containing trx files'
    required: true
  results-group:
    description: ''
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
