name: 'TestSpotlight'
description: 'An easier way to see what broke your code.'
author: 'DuncanScu'
branding:
  icon: 'percent'
  color: 'green'
inputs:
  github-token:
    description: 'GitHub repository token'
    required: true
  comment-title:
    description: 'Pull Request comment title'
    required: false
    default: 'Test Results'
  results-path:
    description: 'Path to the directory containing trx files'
    required: true
  result-groups:
    description: 'Group your results by path adn group name'
    required: false
    type: array
      items:
        type: object
        properties:
          results-path:
            type: string
          group-title:
            type: string

runs:
  using: 'node16'
  main: 'dist/index.js'
